const express = require('express')
const bodyParser = require('body-parser') 
//const response = require('./network/response')
//const router = express.Router() 
//const router = require('./components/message/network')
const router = require('./network/routes')
const app = express()
app.use('/app', express.static('public'))

app.use(bodyParser.urlencoded({extended:false}))
app.use(bodyParser.json())
//app.use(router)
router(app)

app.listen(3000)
console.log('servidor corriendo en puerto 3000')
